name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn add -dev jest
          yarn add -dev jest-environment-jsdom
      - name: Run tests
        run: yarn test
